### ISSUE TITLE
Add support for custom fields to Certificates.enroll

### ISSUE THREAD

**Issue by alextremblay** [broadinstitute/python-cert_manager#24]
Hi @coreone, thank you for all the work you've put into this library. It's immensely helpful!

looking at the source on main, i see you've implemented a getter for custom_fields from the API, but the enroll method does not yet support specifying custom fields.

I've cloned the repo and started working on implementing that feature.

I can submit a PR for a patch that would add this capability. I think i can also implement validation of custom fields marked mandatory

**Comment by coreone** [comment]
A PR is always welcome 😄

**Comment by eis-si-github** [comment]
Hi @coreone, now that all the checks are passing, is there anything else you need me to do before merging this PR?

**Comment by alextremblay** [comment]
Hi @coreone, now that all the checks are passing, is there anything you need me to do before merging this PR?

**Comment by alextremblay** [comment]
Thanks!
