### ISSUE TITLE
PyPi outdated version?

### ISSUE THREAD

**Issue by evilensky** [broadinstitute/python-cert_manager#30]
Will a new version be pushed to PyPi? 

Version 1.0.0 appears to not have support for setting `externalRequester` on  `Certificates._enroll()` method.

Thank you for your time.

**Comment by evilensky** [comment]
"Migrate to poetry" Does this mean the PyPi package is wholly deprecated? https://github.com/broadinstitute/python-cert_manager/blob/c41a2b0ebf258cfe2762b9a127810dbf6e9ff536/pyproject.toml

**Comment by coreone** [comment]
No, this is not meant to say PyPi is deprecated.  We just switched to using Poetry for dependencies and things like automatic `setup.py` generation.  This will still be deployed to PyPi going forward.

I will look into getting a new release setup to get unreleased features into PyPi

**Comment by coreone** [comment]
@evilensky Version 2.0.0 has been released with all features up to today.
